[project]
name = "research-buddy"
version = "0.1.0"
description = "A research assistant using multiple agents"
requires-python = ">=3.9"
dependencies = [
    "openai-agents>=0.0.6",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.rye]
managed = true
dev-dependencies = [] 
